all:
  hosts:
    node1:
      ansible_host: 172.18.7.52
      ip: 172.18.7.52
      access_ip: 172.18.7.52
    node2:
      ansible_host: 172.18.7.53
      ip: 172.18.7.53
      access_ip: 172.18.7.53
    node3:
      ansible_host: 172.18.7.55
      ip: 172.18.7.55
      access_ip: 172.18.7.55
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
