apiVersion: v1
kind: Service
metadata:
  name: registry-nodeport
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: registry
    kubernetes.io/name: KubeRegistry
  namespace: kube-system
spec:
  type: NodePort
  ports:
    - name: registry-nodeport
      nodePort: 30500
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    k8s-app: registry

