# Need to set certmanager-issuer.email before templating
certmanager-issuer:
  email: vasiliy.basov.82@gmail.com

global:
  kubectl:
    image:
      repository: registry.local/gitlab-org/build/cng/kubectl
      tag: v16.6.1
  certificates:
    image:
      repository: registry.local/gitlab-org/build/cng/certificates
      tag: v16.6.1
  gitlabBase:
    image:
      repository: registry.local/gitlab-org/build/cng/gitlab-base
      tag: v16.6.1
  edition: ce
  hosts:
    domain: gitlab.local
    externalIP: 172.18.7.70
  kas:
    enabled: true
  ingress:
    configureCertmanager: false
    class: nginx
gitlab-runner:
  runners:
    privileged: true
  image:
    registry: registry.local
    image: gitlab-org/gitlab-runner
nginx-ingress:
  enabled: false
#  controller: *custom
certmanager:
  install: false
#  <<: *custom
#  cainjector: *custom

shared-secrets:
  selfsign:
    image: 
      repository: registry.local/gitlab-org/build/cng/cfssl-self-sign

# global:
#   certificates:
#     image:
#       repository: registry.local/gitlab-org/build/cngcertificates
#   kubectl:
#     image:
#       repository: registry.local/gitlab-org/build/cngkubectl
#   gitlabBase:
#     image:
#       repository: registry.local/gitlab-org/build/cnggitlab-base

gitlab:
  geo-logcursor:
    image:
      repository: registry.local/gitlab-org/build/cng/gitlab-geo-logcursor
      tag: v16.6.1
  gitaly:
    image:
      repository: registry.local/gitlab-org/build/cng/gitaly
      tag: v16.6.1
  gitlab-exporter:
    image:
      repository: registry.local/gitlab-org/build/cng/gitlab-exporter
      tag: v16.6.1
  gitlab-pages:
    image:
      repository: registry.local/gitlab-org/build/cng/gitlab-pages
      tag: v16.6.1
  gitlab-shell:
    image:
      repository: registry.local/gitlab-org/build/cng/gitlab-shell
      tag: v16.6.1
  mailroom:
    image:
      repository: registry.local/gitlab-org/build/cng/gitlab-mailroom
      tag: v16.6.1
  migrations:
    image:
      repository: registry.local/gitlab-org/build/cng/gitlab-toolbox-ce
      tag: v16.6.1
  praefect:
    image:
      repository: registry.local/gitlab-org/build/cng/gitaly
      tag: v16.6.1
  sidekiq:
    image:
      repository: registry.local/gitlab-org/build/cng/gitlab-sidekiq-ce
      tag: v16.6.1
  toolbox:
    image:
      repository: registry.local/gitlab-org/build/cng/gitlab-toolbox-ce
      tag: v16.6.1
  webservice:
    image:
      repository: registry.local/gitlab-org/build/cng/gitlab-webservice-ce
      tag: v16.6.1
    workhorse:
      image: registry.local/gitlab-org/build/cng/gitlab-workhorse-ce
      tag: v16.6.1
  gitlab-kas:
    image:
      repository: registry.local/gitlab-org/build/cng/gitlab-kas
      tag: v16.6.0
  kas:
    image:
      repository: registry.local/gitlab-org/build/cng/gitlab-kas
      tag: v16.6.0
# --- Charts from requirements.yaml ---

minio:
  image: registry.local/minio/minio
  imageTag: "RELEASE.2017-12-28T01-21-00Z"
  minioMc:
    image: registry.local/minio/mc
    tag: "RELEASE.2018-07-13T00-53-22Z"

registry:
  image:
    repository: registry.local/gitlab-org/build/cng/gitlab-container-registry
    tag: 'v3.86.1-gitlab'

postgresql:
  image:
    registry: registry.local
    repository: bitnami/postgresql
    tag: 15.3.0-debian-11-r0 # start with number to make checkConfig happy
  metrics:
    image:
      registry: registry.local
      repository: bitnami/postgres-exporter
      tag: 0.12.0-debian-11-r86

prometheus:
  server:
    image:
      repository: registry.local/prometheus/prometheus
      tag: v2.38.0
  configmapReload:
    prometheus:
      image:
        repository: registry.local/jimmidyson/configmap-reload
        tag: v0.5.0

redis:
  image:
    registry: registry.local
    repository: bitnami/redis
    tag: 6.2.7-debian-11-r11
  metrics:
    image:
      registry: registry.local
      repository: bitnami/redis-exporter
      tag: 1.43.0-debian-11-r4

# upgradeCheck: *custom
