kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: hdd-local-sztu-esxi-06
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
allowVolumeExpansion: true # Optional: only applicable to vSphere 7.0U1 and above
# При использовании Retain, ресурсы хранилища, связанные с PVC, не удаляются при удалении PVC
# В этом случае, если PVC удаляется, PV остается неизменным, и администратор кластера должен вручную принимать решение о том, что делать с PV.
reclaimPolicy: Retain
parameters:
  datastoreurl: "ds:///vmfs/volumes/609a5210-6f88d68a-f4fe-c4ff1fba6924"
  storagepolicyname: "Kuber-VMFS-hdd-local-sztu-esxi-06"
  csi.storage.k8s.io/fstype: ext4
