apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-local-sztu-esxi-06
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: csi.vsphere.vmware.com
allowVolumeExpansion: true # Optional: only applicable to vSphere 7.0U1 and above
# При использовании Retain, ресурсы хранилища, связанные с PVC, не удаляются при удалении PVC
# В этом случае, если PVC удаляется, PV остается неизменным, и администратор кластера должен вручную принимать решение о том, что делать с PV.
reclaimPolicy: Retain
# Должна быть создана storagepolicyname заранее в VMWARE - Policies and Profiles - VM Storage Policies
parameters:
  csi.storage.k8s.io/fstype: ext4
  datastoreurl: ds:///vmfs/volumes/5c66a4b3-3bfa253c-b58f-f86eee838e11/
  storagepolicyname: Kuber-VMFS

