apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-secret
  namespace: gitlab-runner
type: Opaque
data:
  # Замените на свой зашифрованный base64 токен
  # echo -n "token" | base64
  runner-registration-token: 123123123123123dqwd
  # Если используете приватный registry
  # .dockerconfigjson: <base64_encoded_docker_config>
