controller:
  # Файл конфигурации, записывает в configmap
  config:
    # Не нужно в access-log писать запросы к health check-ам (kubelet раз в 15 секунд делает эти запросы)
    skip-access-log-urls: /health,/healthz,/ping
    # Когда меняется конфигурация ingress controller то reload-ся nginx
    # а старая версия обрабатывает запросы и может висеть часами, эта настройка убивает старую версию nginx через 30 сек
    worker-shutdown-timeout: "30"
  

  # -- Optionally change this to ClusterFirstWithHostNet in case you have 'hostNetwork: true'.
  # By default, while using host network, name resolution uses the host's DNS. If you wish nginx-controller
  # to keep resolving names inside the k8s network, use ClusterFirstWithHostNet.
  dnsPolicy: ClusterFirstWithHostNet

  # -- This configuration defines if Ingress Controller should allow users to set
  # their own *-snippet annotations, otherwise this is forbidden / dropped
  # when users add those annotations.
  # Global snippets in ConfigMap are still respected
  allowSnippetAnnotations: true

  # -- Required for use with CNI based kubernetes installations (such as ones set up by kubeadm),
  # since CNI and hostport don't mix yet. Can be deprecated once https://github.com/kubernetes/kubernetes/issues/23920
  # is merged
  # Внутри подов прописан сетевой namespace узла, (Более простой и быстрый вариант если не настроен Load Balancer)
  hostNetwork: true

  # -- Election ID to use for status update
  electionID: ingress-controller-leader

  replicaCount: 1
  # Выставляем приоритет для того чтобы не вырубило nginx controller если не будет хватать ресурсов
  # kubectl get pc
  priorityClassName: "system-cluster-critical"
## If true, create & use Pod Security Policy resources
## https://kubernetes.io/docs/concepts/policy/pod-security-policy/
podSecurityPolicy:
  enabled: true
