envFromSecret: "telegraf-tokens"

# Конфиг telegraf.conf будет преобразовываться из yaml в toml формат:
config:
  agent:
    interval: "5s"
  outputs:
    - influxdb_v2:
        urls:
          - "http://influxdb-influxdb2.monitoring.svc.cluster.local:8086"
        token: "$INFLUXDB_TOKEN"
        organization: "sztu"
        bucket: "default"
  inputs:
    - vsphere:
        vcenters: 
          - "https://192.168.0.1/sdk"
        username: "$VSPHERE_USERNAME"
        password: "$VSPHERE_PASSWORD"
        insecure_skip_verify: true
        vm_metric_include:
          - "cpu.demand.average"
          - "cpu.idle.summation"
          - "cpu.demand.average"
          - "cpu.idle.summation"
          - "cpu.latency.average"
          - "cpu.readiness.average"
          - "cpu.ready.summation"
          - "cpu.run.summation"
          - "cpu.usagemhz.average"
          - "cpu.used.summation"
          - "cpu.wait.summation"
          - "mem.active.average"
          - "mem.granted.average"
          - "mem.latency.average"
          - "mem.swapin.average"
          - "mem.swapinRate.average"
          - "mem.swapout.average"
          - "mem.swapoutRate.average"
          - "mem.usage.average"
          - "mem.vmmemctl.average"
          - "net.bytesRx.average"
          - "net.bytesTx.average"
          - "net.droppedRx.summation"
          - "net.droppedTx.summation"
          - "net.usage.average"
          - "power.power.average"
          - "virtualDisk.numberReadAveraged.average"
          - "virtualDisk.numberWriteAveraged.average"
          - "virtualDisk.read.average"
          - "virtualDisk.readOIO.latest"
          - "virtualDisk.throughput.usage.average"
          - "virtualDisk.totalReadLatency.average"
          - "virtualDisk.totalWriteLatency.average"
          - "virtualDisk.write.average"
          - "virtualDisk.writeOIO.latest"
          - "sys.uptime.latest"
        host_metric_include:
          - "cpu.coreUtilization.average"
          - "cpu.costop.summation"
          - "cpu.demand.average"
          - "cpu.idle.summation"
          - "cpu.latency.average"
          - "cpu.readiness.average"
          - "cpu.ready.summation"
          - "cpu.swapwait.summation"
          - "cpu.usage.average"
          - "cpu.usagemhz.average"
          - "cpu.used.summation"
          - "cpu.utilization.average"
          - "cpu.wait.summation"
          - "disk.deviceReadLatency.average"
          - "disk.deviceWriteLatency.average"
          - "disk.kernelReadLatency.average"
          - "disk.kernelWriteLatency.average"
          - "disk.numberReadAveraged.average"
          - "disk.numberWriteAveraged.average"
          - "disk.read.average"
          - "disk.totalReadLatency.average"
          - "disk.totalWriteLatency.average"
          - "disk.write.average"
          - "mem.active.average"
          - "mem.latency.average"
          - "mem.state.latest"
          - "mem.swapin.average"
          - "mem.swapinRate.average"
          - "mem.swapout.average"
          - "mem.swapoutRate.average"
          - "mem.totalCapacity.average"
          - "mem.usage.average"
          - "mem.vmmemctl.average"
          - "net.bytesRx.average"
          - "net.bytesTx.average"
          - "net.droppedRx.summation"
          - "net.droppedTx.summation"
          - "net.errorsRx.summation"
          - "net.errorsTx.summation"
          - "net.usage.average"
          - "power.power.average"
          - "storageAdapter.numberReadAveraged.average"
          - "storageAdapter.numberWriteAveraged.average"
          - "storageAdapter.read.average"
          - "storageAdapter.write.average"
          - "sys.uptime.latest"
