apiVersion: v1
kind: Secret
metadata:
  name: telegraf-tokens
  namespace: monitoring  # Убедитесь, что это правильный namespace
type: Opaque
# Перевести в Base64: echo -n 'your_value' | base64
# Расшифровать: echo 'U29tZSBzdHJpbmc=' | base64 --decode
data:
  influxdb_token: "OExZcC9Senh1WG85eUR1Vk9FUDBkcWQxbDU1cERUMkREQ21q" # Base64-encoded токен
  vsphere_username: "YWRtaW5pc3RyYXRvckB2c3BoZXJlLmxvY2Fs" # Base64-encoded username
  vsphere_password: "cGFzc3dvcmRfaGVyZQ==" # Base64-encoded password
